service:
  name: express-ts-demo

component: aws-iam-role
name: backend-permissions

inputs:
  name: ${name}-${env:STAGE}
  region: ${env:AWS_REGION}
  service: lambda.amazonaws.com
  policy:
    # Marketing API Logs and Assume Role access
    - Effect: Allow
      Action:
        - sts:AssumeRole
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    # Marketing Database access
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${env:AWS_REGION}:*:table/backend-db-${env.STAGE}
        - arn:aws:dynamodb:${env:AWS_REGION}:*:table/backend-db-${env.STAGE}/index/*
